# -*- coding: utf-8 -*-
"""SonarData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r04bEdqsVXvf85rj7tGa0NNQkuQHMsMH
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

data = pd.read_csv('./sonarData.csv', header=None)
data.head()
data.shape
data.describe()
data[60].value_counts()
data.groupby(60).mean()
X = data.drop(columns=60, axis=1)
Y = data[60]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1, stratify=Y)
model = LogisticRegression()
model.fit(X_train, Y_train)
X_train_prediction = model.predict(X_train)
print(X_train_prediction)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy on training data : ', training_data_accuracy*100)